mutation loginLandlord($login: LoginLandlordInput!){
	loginLandlord(login: $login) {
        id
        firstName,
        lastName,
        phoneNumber,
        email,
        profileURL,
        state,
        deviceId,
        landlordAddress {
            city, 
            poBox, 
            postalCode, 
            province, 
            streetName, 
            streetNumber, 
            unitNumber
        }
    }
}