mutation updateRentDeposits($houseId: Int!, $rentDeposits: [RentDepositInput!]!){
   updateRentDeposits(houseId: $houseId, rentDeposits: $rentDeposits) {
        name,
        amount,
        details {
            detail
        }   
    }
}