mutation updateServices($houseId: Int!, $services: [ServiceInput!]!) {
   updateServices(houseId: $houseId, services: $services) {
        name,
        isIncludedInRent,
        isPayPerUse,
        details {
            detail
        }         
  }
}