mutation updateAdditionalTerms($houseId: Int!, $additionalTerms: [AdditionalTermInput!]!) {
   updateAdditionalTerms(houseId: $houseId, additionalTerms: $additionalTerms) {
        name,
        details {
            detail
        }   
  }
}